# Generated by Django 5.0.3 on 2024-04-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Product_name',
        ),
    ]
