# Generated by Django 5.0.3 on 2024-04-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('staples', 'Staples'), ('snacks_&_beverages', 'Snacks and Beverages'), ('household_items', 'Household Items'), ('dairy_and_eggs', 'Dairy and Eggs')], max_length=55),
        ),
    ]
