# Generated by Django 5.0.3 on 2024-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_contactmessage_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(default=False, max_length=6),
            preserve_default=False,
        ),

    ]
