# Generated by Django 5.0.3 on 2024-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_address_customuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
