# Generated by Django 5.0.3 on 2024-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_address_customuser_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
