# Generated by Django 5.0.3 on 2024-04-12 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
    ]
