# Generated by Django 5.0.3 on 2024-04-12 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='upi_id',
        ),
    ]
