# Generated by Django 5.0.3 on 2024-04-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
